
language: python

python:
 - "3.5"
          
addons:
  apt:
    packages:
      - libudunits2-dev
      - libproj-dev
      - libgeos-dev
      - libgdal-dev


install: pip install -e src/

script: pytest
